# Generated by Django 5.2.17 on 2026-10-05 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_post_post_type_contentreport_moderationaction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[
                            (1, "Very Easy"),
                            (2, "Easy"),
                            (3, "Medium"),
                            (4, "Hard"),
                            (5, "Very Hard"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "offer_status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Offer Accepted"),
                            ("REJECTED", "Offer Rejected"),
                            ("PENDING", "Pending"),
                            ("NO_OFFER", "No Offer"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_experiences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("INTERNSHIP", "Internship"),
                            ("PART_TIME", "Part Time"),
                            ("CONTRACT", "Contract"),
                        ],
                        default="FULL_TIME",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("apply_link", models.URLField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
